%--------------------------------------------------------------------------
% ANÁLISIS MORFOLÓGIACO DE LA CIRCULARIDAD
%--------------------------------------------------------------------------
function h = grafAnalisisMorfo(CSF,ESF)
%H=GRAFANALISISMORFO(CSF,ESF)
%
%   Entrada
%       CSF     Coefisiente de circularidad
%       ESF     Coeficiente elíptico
%   Salida
%       h       handle de la grafifica 
%

screenSize = get(0,'ScreenSize');
pointsPerPixel = 72/get(0,'ScreenPixelsPerInch');

width  = 450 * pointsPerPixel;
height = 450 * pointsPerPixel;
pos = [screenSize(3)/2-width/2 screenSize(4)/2-height/2 width height];

f = figure(...
    'Units', 'points', ...
    'BusyAction', 'queue', ...
    'Position', pos, ...
    'Resize','off', ...
    'CreateFcn','', ...
    'NumberTitle','off', ...
    'IntegerHandle','off', ...
    'MenuBar', 'none', ...
    'Tag','TMWWaitbar',...
    'Interruptible', 'off', ...
    'WindowStyle', 'normal', ...
    'DockControls', 'off', ...
    'Visible','on');


% Creando la axesisa de la grafica donde mostraran las estadisticas de la
% morfologia de la imagen. 
axFontSize  = get(0,'FactoryAxesFontSize');
%axPos       = [100 100 300 300];

axNorm = [0.2 0.2 1.0 1.0];
axPos  = axNorm.*[pos(3:4),pos(3:4)];

h = axes('XLim',[0 100],...
            'Tag','axesAnalisis',...
            'DrawMode','fast',...
            'Color',[1 1 1],...
            'XLim',[0 1],...
            'YLim',[0 1],...
            'Box','on', ...
            'Units','Pixel',...
            'FontSize', axFontSize,...
            'Position',axPos,...            
            'XTickMode','manual',...
            'YTickMode','manual',...
            'XTick',[0:0.1:1],...
            'YTick',[0:0.1:1],...
            'XTickLabelMode','auto',...           
            'YTickLabelMode','auto');
         
        
set(get(h,'XLabel'),'String','CSF');
set(get(h,'YLabel'),'String','ESF');

line([.8 .8],[.0 1.0],'LineStyle','-');
line([.0 1.0],[.5 .5],'LineStyle','-');

% Análisis de la forma de los objetos en cuanto a su esfericidad 
ELONG = ESF < 0.5;             % deformadas alargadas
OTRAS = ESF > 0.5 & CSF < 0.8; % deformadas poco alargadas en las que se incluyen estrellada y hoja
DISC  = ESF > 0.5 & CSF > 0.8; % se considera discoidales normales

hold on
hp=plot(h,CSF(DISC) ,ESF(DISC)  ,'ro', ...
          CSF(ELONG),ESF(ELONG) ,'b*',...
          CSF(OTRAS),ESF(OTRAS) ,'g+');    
hold off


hl=legend(hp,'Circulares','Elongadas','Otras deformaciones',2);
set(hl, 'Interpreter','none');





