


figure;
axFontSize=get(0,'FactoryAxesFontSize');
axPos = [100 100 300 300];
h = axes('XLim',[0 100],...
            'Tag','axesAnalisis',...
            'DrawMode','fast',...
            'Color',[1 1 1],...
            'XLim',[0 1],...
            'YLim',[0 1],...
            'Box','on', ...
            'Units','Pixel',...
            'FontSize', axFontSize,...
            'Position',axPos,...            
            'XTickMode','manual',...
            'YTickMode','manual',...
            'XTick',[0:0.1:1],...
            'YTick',[0:0.1:1],...
            'XTickLabelMode','auto',...           
            'YTickLabelMode','auto');
         
        
set(get(h,'XLabel'),'String','CSF');
set(get(h,'YLabel'),'String','ESF');

line([.8 .8],[.0 1.0],'LineStyle','-');
line([.0 1.0],[.5 .5],'LineStyle','-');


CSFC = [0.9 0.5 0.6 0.7];
ESFC = [0.8 0.4 0.6 0.9];


CSFE = [0.5 0.7 0.1 0.7];
ESFE = [0.1 0.9 0.6 0.4];

hold on
hp=plot(CSFC,ESFC,'ro',CSFE,ESFE,'b*');
hold off
h=legend(hp,'Circulares','Elongadas',2);
set(h, 'Interpreter','none');





